name: lighthouse_pm
description: Power management app to control the steam lighthouses from your phone
homepage: https://github.com/jeroen1602/lighthouse_pm

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+8

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  package_info_plus: ^4.0.1
  permission_handler: ^10.2.0
  flutter_svg: ^2.0.4
  url_launcher: ^6.1.10
  community_material_icon: 5.9.55
  dynamic_color: ^1.6.3
  mutex: ^3.0.1
  convert: ^3.1.1
  vibration: ^1.7.7
  toast: ^0.3.0
  drift: ^2.6.0
  sqlite3_flutter_libs: ^0.5.13
  path_provider: ^2.0.14
  path: ^1.8.2
  provider: ^6.0.5
  tuple: ^2.0.1
  intl: ^0.18.0
  device_info_plus: ^8.1.0
  meta: ^1.8.0
  flutter_markdown: ^0.6.14
  markdown: ^7.0.1
  # Android/ iOS
  flutter_reactive_ble_back_end:
    path: lighthouse_provider/lighthouse_back_ends/flutter_reactive_ble_back_end
  # Web:
  flutter_web_bluetooth: ^0.2.0
  web_browser_detect: ^2.0.3
  flutter_web_bluetooth_back_end:
    path: lighthouse_provider/lighthouse_back_ends/flutter_web_bluetooth_back_end
  # Linux:
  bluez_back_end:
    path: lighthouse_provider/lighthouse_back_ends/bluez_back_end
  # lighthouse provider
  lighthouse_provider:
    path: lighthouse_provider/lighthouse_provider
  lighthouse_back_end:
    path: lighthouse_provider/lighthouse_back_end
  lighthouse_providers:
    path: lighthouse_provider/lighthouse_providers
  fake_back_end:
    path: lighthouse_provider/lighthouse_back_ends/fake_back_end
  shared_platform:
    path: shared/shared_platform
  lighthouse_logger:
    path: lighthouse_provider/lighthouse_logger

  # This may need to be enabled again if the build runner doesn't like it.
  #dependency_overrides:
  #  analyzer: 0.39.14


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.6.0
  build_runner: 2.3.3
  flutter_lints: ^2.0.1
  lighthouse_test_helper:
    path: lighthouse_provider/lighthouse_test_helper

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/app-icon.svg
    - assets/images/identify-icon.svg
    - assets/images/github-dark.svg
    - assets/images/github-light.svg
    - assets/images/drawer-image.png
    - assets/images/group-add-icon.svg
    - assets/images/group-edit-icon.svg
    - assets/images/group-delete-icon.svg
    - assets/images/nickname-icon.svg
    - assets/images/f-droid-logo.svg
    - assets/images/paypal.svg
    - assets/images/github-sponsors.svg
    - assets/pages/privacy/
    - assets/pages/help/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
