name: lighthouse_providers
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter_web_bluetooth: ^1.0.0
  meta: ">=1.3.0 <2.0.0"
  rxdart: ">=0.28.0 <1.0.0"
  lighthouse_provider:
    path: ../lighthouse_provider
  lighthouse_back_end:
    path: ../lighthouse_back_end
  shared_platform:
    path: ../../shared/shared_platform
  lighthouse_logger:
    path: ../lighthouse_logger

dev_dependencies:
  lints: ">=5.1.0 <6.0.0"
  test: ">=1.25.12 < 2.0.0"
  fake_back_end:
    path: ../lighthouse_back_ends/fake_back_end
  lighthouse_test_helper:
    path: ../lighthouse_test_helper
