name: shared_platform
description: A library that helps with making platform specific code paths available for web and io builds.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  meta: ">=1.16.0 <2.0.0"

dev_dependencies:
  lints: ">=5.1.0 <6.0.0"
  test: ">=1.25.12 < 2.0.0"
