name: lighthouse_test_helper
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  meta: ">=1.16.0 <2.0.0"
  rxdart: ">=0.28.0 <1.0.0"
  shared_platform:
    path: ../../shared/shared_platform
  fake_back_end:
    path: ../lighthouse_back_ends/fake_back_end
  lighthouse_back_end:
    path: ../lighthouse_back_end
  lighthouse_provider:
    path: ../lighthouse_provider
  lighthouse_providers:
    path: ../lighthouse_providers
  test: ">=1.24.9 < 2.0.0"

dev_dependencies:
  lints: ">=5.1.0 <6.0.0"
