name: lighthouse_logger
description: A logger for the lighthouse packages
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  logging: ">=1.3.0 <2.0.0"

dev_dependencies:
  lints: ">=5.1.0 <6.0.0"
  test: ">=1.25.12 < 2.0.0"
